-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgI1wa+zyEmfLoTPLK
mBKXcZcMNlWtCF7MVi5+tzYZYRmgCgYIKoZIzj0DAQehRANCAARlQSIgE5j1toRK
tdoMS1ghtwHyuStEsdy9MGhzFOFbYT0TctmiPhdFVnbkVXYaKslI2F5g3MmV7QsN
8FPbQMRs
-----END PRIVATE KEY-----